/**
 * ข้อ p3 และชื่อเรื่องต่อคัมภีร์ (ภาค ๓) — สอดคล้องกับ index ในแต่ละโฟลเดอร์
 * สร้างด้วย: python scripts/gen_part3_pitaka_passages_ts.py
 */
export const PART3_PITAKA_PASSAGES = {
  'vinaya-pitaka': [
    { id: 33, title: "ภิกษุที่ภิกษุด้วยกันไม่พึงไหว้ ๕ ประเภท", anchor: "x2g8VhoqBT" },
    { id: 34, title: "ภิกษุที่ภิกษุด้วยกันไม่พึงไหว้อีก ๕ ประเภท", anchor: "7sx2u6sswa" },
    { id: 35, title: "ภิกษุที่ภิกษุด้วยกันไม่พึงไหว้อีก ๕ ประเภท", anchor: "BdC3hKRlbZ" },
    { id: 36, title: "บุคคลที่ภิกษุไม่พึงไหว้อีก ๕ ประเภท", anchor: "4Uhxdie2Ek" },
    { id: 37, title: "ภิกษุที่ภิกษุด้วยกันไม่พึงไหว้อีก ๕ ประเภท", anchor: "aSLWzuAKjM" },
    { id: 38, title: "คุณสมบัติ ๖ อย่างของภิกษุผู้ควรเป็นอุปัชฌายะ", anchor: "oGtFH3c9S7" },
    { id: 39, title: "คุณสมบัติอีก ๖ อย่างของภิกษุผู้ควรเป็นอุปัชฌายะ", anchor: "QziURSWM20" },
    { id: 40, title: "คุณสมบัติอีก ๖ อย่างของภิกษุผู้ควรเป็นอุปัชฌายะ", anchor: "8vLksq1zIU" },
    { id: 41, title: "คุณสมบัติอีก ๖ อย่างของภิกษุผู้ควรเป็นอุปัชฌายะ", anchor: "Crl4Hkn6Iy" },
    { id: 42, title: "คุณสมบัติอีก ๖ อย่างของภิกษุผู้ควรเป็นอุปัชฌายะ", anchor: "NuEcynvC1H" },
    { id: 43, title: "คุณสมบัติอีก ๖ อย่างของภิกษุผู้ควรเป็นอุปัชฌายะ", anchor: "PflW0Js2JM" },
    { id: 44, title: "คุณสมบัติอีก ๖ อย่างของภิกษุผู้ควรเป็นอุปัชฌายะ", anchor: "5EAfcWqYH1" },
    { id: 83, title: "ประวัติความเป็นมาของนางภิกษุณี", anchor: "FJ60tS7NsF" },
    { id: 112, title: "พระพุทธเจ้าทรงพยาบาลภิกษุอาพาธ", anchor: "vffp2zGo85" },
    { id: 138, title: "ผ้าเช็ดเท้า", anchor: "oB83STnpXt" },
    { id: 139, title: "ห้ามเหยียบเสนาสนะทั้งที่เท้าเปื้อน", anchor: "4Y6siafxHT" },
    { id: 140, title: "ห้ามเหยียบเสนาสนะทั้งที่เท้าเปียก", anchor: "5XA8EA03hd" },
    { id: 141, title: "ห้ามใส่รองเท้าเหยียบเสนาสนะ", anchor: "a23fkjujoI" },
    { id: 142, title: "ห้ามบ้วนน้ำลายบนพื้นที่ทาสี", anchor: "yHg99NbYQA" },
    { id: 143, title: "ให้ใช้ผ้าพันเท้าเตียงเท้าตั่ง", anchor: "MRlOIGsG7C" },
    { id: 144, title: "ห้ามพิงฝาที่ทาสี", anchor: "tKCYq1TQ6m" },
    { id: 145, title: "อนุญาตให้ใช้เครื่องปูนอน", anchor: "p9NdkyPHQG" },
    { id: 169, title: "คมิกวัตร (ข้อปฏิบัติสำหรับภิกษุผู้จะเดินทางจากไป)", anchor: "UkdE58lilq" },
    { id: 170, title: "เสนาสนวัตร (ข้อปฏิบัติเกี่ยวกับที่อยู่อาศัย)", anchor: "14cwHKyKsz" },
  ] as const,
  'digha-nikaya': [
    { id: 137, title: "พระอรหันต์ไม่ก้าวล่วงฐานะ ๙ ประการ", anchor: "d3kG5taKVS" },
    { id: 219, title: "ตรัสแนะนำให้สังคายนาพระธรรมวินัย", anchor: "e0EMVKnmKB" },
    { id: 220, title: "การทำตนให้ชุ่มด้วยความสุข", anchor: "wnikh2crZD" },
    { id: 221, title: "พราหมณ์เกิดจากปากพรหมแน่หรือ", anchor: "AWWKyNstnc" },
    { id: 222, title: "วรรณะ ๔ มีทั้งที่ทำชั่วทำดี", anchor: "5z49SGoOq2" },
    { id: 223, title: "ตรัสเล่าเรื่องพระเจ้าปเสนทิโกศลปฏิบัติต่อพระองค์", anchor: "4Bged4vHyo" },
    { id: 225, title: "อย่าโกรธเมื่อใครติเตียนพระพุทธเจ้า", anchor: "ITVj6F2ZXL" },
    { id: 226, title: "อย่าดีใจตื่นเต้นเมื่อใครชมเชยพระพุทธเจ้า", anchor: "ecd9989VUz" },
  ] as const,
  'majjhima-nikaya': [
    { id: 1, title: "อะไรเป็นแก่นสารในพระพุทธศาสนา", anchor: "hLrd1Z9qoJ" },
    { id: 117, title: "ต้องเป็นผู้รู้ ผู้เห็น จึงสิ้นอาสวะได้", anchor: "ao0NIHb3Pm" },
  ] as const,
  'samyutta-nikaya': [
    { id: 146, title: "ไม่เที่ยง เป็นทุกข์ ไม่ใช่ตัวตน", anchor: "55O57WVkit" },
    { id: 147, title: "ผู้ชื่นชมทุกข์", anchor: "bJXtVh55JA" },
    { id: 148, title: "ความเกิด ความดับ แห่งทุกข์", anchor: "AGIhxTi4bA" },
    { id: 149, title: "ตา หู เป็นต้น มีที่ไหน มารมีที่นั่น", anchor: "pF2aI3Arbc" },
    { id: 150, title: "นรกที่ตา หู เป็นต้น", anchor: "mS2Vqa3UPM" },
    { id: 151, title: "สวรรค์ที่ตา หู เป็นต้น", anchor: "g14angsGbv" },
    { id: 152, title: "เวียนว่ายตายเกิด", anchor: "YgJd4tBuW3" },
    { id: 173, title: "จิต มโน วิญญาณ เกิดดับ", anchor: "dSPhkBW9pt" },
    { id: 174, title: "เข้ากันได้โดยธาตุ", anchor: "0CbRjlNJDa" },
    { id: 175, title: "ตัวอย่างของผู้เข้ากันได้โดยธาตุ", anchor: "gPSYuwZKkW" },
    { id: 176, title: "เรื่องที่มิได้ตรัสบอกมีมากกว่า", anchor: "dY6lW4oybH" },
    { id: 177, title: "เรื่องที่ตรัสบอกคืออะไร", anchor: "VXzSVG63dn" },
    { id: 178, title: "ใบไม้ขนาดเล็กที่ห่อน้ำหรือห่อใบตาลไม่ได้", anchor: "6lAVr8e4Xd" },
    { id: 179, title: "ธรรมที่เป็นใหญ่คือปัญญา เทียบด้วยราชสีห์", anchor: "OvQawCMzu4" },
    { id: 180, title: "กายไม่หวั่นไหว จิตไม่หวั่นไหว", anchor: "pxfFBu24rp" },
    { id: 181, title: "เมื่อก่อนตรัสรู้ ทรงเจริญอานาปานสติมาก", anchor: "FaHTDHzHa9" },
    { id: 182, title: "เมื่อตรัสรู้แล้ว ทรงอยู่ด้วยอานาปานสติโดยมาก", anchor: "dvQtWVGWQV" },
    { id: 183, title: "อริยวิหาร พรหมวิหาร ตถาคตวิหาร", anchor: "kCK42Vrrfc" },
    { id: 184, title: "พระอรหันต์เจริญอานาปานสติทำไม", anchor: "TqfjXVZ69N" },
    { id: 185, title: "เจริญธรรมอย่างเดียว ชื่อว่าเจริญธรรมอย่างอื่นอีกมาก", anchor: "BfBV9lPpLT" },
    { id: 199, title: "ปฏิบัติได้แค่ไหน อะไรสงบระงับ", anchor: "6biuxZOpZi" },
    { id: 200, title: "ความดับแห่งเครื่องปรุงแต่งตามลำดับชั้น", anchor: "VJTXpkSoIC" },
    { id: 201, title: "บุถุชนกับอริยสาวกต่างกันอย่างไร", anchor: "ttuu4lDmrU" },
    { id: 202, title: "สตรีที่บุรุษไม่ชอบใจเลย", anchor: "W0qVTpMq8T" },
    { id: 203, title: "สตรีที่บุรุษชอบใจแท้", anchor: "J4j3nOtpbl" },
    { id: 204, title: "บุรุษที่สตรีไม่ชอบใจเลย", anchor: "VUboP0mlVr" },
    { id: 205, title: "บุรุษที่สตรีชอบใจแท้", anchor: "trTxPYBzK0" },
    { id: 206, title: "ความทุกข์โดยเฉพาะของสตรี", anchor: "zSKhV7R3KP" },
    { id: 207, title: "กำลัง ๕ ของสตรี", anchor: "On9Rc0v9Lk" },
    { id: 208, title: "บุรุษประกอบด้วยอะไรจึงครอบงำสตรีได้", anchor: "C60EafaEPn" },
    { id: 211, title: "เวทนา ๒ ถึง ๑๐๘", anchor: "wBOM8a0tZH" },
    { id: 212, title: "เน่าในคืออะไร", anchor: "cigK73IfSi" },
    { id: 213, title: "การบัญญัติความสุขในพระพุทธศาสนา", anchor: "cI8YYei0c6" },
    { id: 214, title: "กายเดือดร้อน อย่าให้จิตเดือดร้อน", anchor: "VoUiKzBtDH" },
    { id: 215, title: "พระอานนท์ตรัสรู้ธรรมเพราะฟังธรรมของใคร", anchor: "K8VvVjZciU" },
    { id: 216, title: "คว่ำหน้ากิน แหงนหน้ากิน เป็นต้น", anchor: "S7FHA30obx" },
    { id: 217, title: "พระพุทธเจ้าทรงปวารณาพระองค์", anchor: "vCnHqmA4WX" },
    { id: 218, title: "ยังยึดถือ จะชื่อว่าไม่มีโทษไม่มี", anchor: "zJvbiTiIE7" },
    { id: 224, title: "เรื่องของพราหมณ์ผู้กระด้างเพราะถือตัว", anchor: "cgQlkXm2pd" },
  ] as const,
  'anguttara-nikaya': [
    { id: 15, title: "ผู้กล่าวตู่ (หาความ) พระตถาคต", anchor: "6OEXFPYiwG" },
    { id: 16, title: "ธรรมที่เป็นไปในส่วนแห่งความรู้ (วิชชาภาคิยะ)", anchor: "NnocnbFuJK" },
    { id: 19, title: "ความเสื่อมที่เลวร้าย ความเจริญที่เป็นยอด", anchor: "Avnw3l5kCm" },
    { id: 20, title: "จิตผ่องใสเศร้าหมองได้ หลุดพ้นได้", anchor: "u1XSvX2mCd" },
    { id: 21, title: "การอบรมจิตของบุถุชนผู้มิได้สดับ และอริยสาวกผู้ได้สดับ", anchor: "WFyRtSeyu0" },
    { id: 22, title: "เมตตาจิตชั่วเวลาลัดนิ้วมือเดียว", anchor: "cA89KZwmCq" },
    { id: 23, title: "กุศล อกุศล มีใจเป็นหัวหน้า", anchor: "LnjlP7IYff" },
    { id: 24, title: "ผู้ให้ กับ ผู้รับ (ทายก กับ ปฏิคาหก)", anchor: "7qOhp04Ujx" },
    { id: 25, title: "ผู้ปรารภความเพียร กับ ผู้เกียจคร้าน", anchor: "TheT7V0JgI" },
    { id: 26, title: "โทษทั้งหลายมีมิจฉาทิฏฐิเป็นอย่างยิ่ง", anchor: "xMwurduUax" },
    { id: 27, title: "ภพ (ความวนเวียนเป็นนั่นเป็นนี่) เปรียบเหมือนอุจจาระ", anchor: "zFLsvl3v5r" },
    { id: 28, title: "ผลของสุจริตและทุจจริต", anchor: "deUZPZNUBB" },
    { id: 29, title: "กายคตาสติ เปรียบเหมือนมหาสมุทร", anchor: "NrUObzcm9A" },
    { id: 30, title: "กายคตาสติ ทำให้ได้อะไรบ้าง", anchor: "wkq6IDwSl0" },
    { id: 31, title: "อานิสงส์ต่าง ๆ ของกายคตาสติ", anchor: "rXpk2gxbkF" },
    { id: 32, title: "กายคตาสติ กับ อมตะ", anchor: "RDc2wAygB9" },
    { id: 45, title: "คนไข้ที่พยาบาลยาก และพยาบาลง่าย", anchor: "WI1nTrOGwN" },
    { id: 46, title: "คนพยาบาลไข้ที่ดี และไม่ดี", anchor: "1NWj1qJfVV" },
    { id: 47, title: "ฐานะ ๕ ที่ควรพิจารณาเนือง ๆ", anchor: "ni8kubDgz7" },
    { id: 48, title: "เหตุผลที่ควรพิจารณาฐานะ ๕ เนือง ๆ", anchor: "vIZA61F97b" },
    { id: 49, title: "ผู้หลับน้อยตื่นมากในราตรี", anchor: "yVsmxgBJ63" },
    { id: 50, title: "ผู้ตกนรก", anchor: "ITqMeEc5u4" },
    { id: 51, title: "ผู้ขึ้นสวรรค์", anchor: "fPIgHIulFl" },
    { id: 52, title: "สัปปุริสทาน ๕ พร้อมทั้งอานิสงส์", anchor: "ZPERC1jEeX" },
    { id: 53, title: "ลักษณะ ๕ ของวาจาสุภาษิต", anchor: "B9Nt0aY4hr" },
    { id: 54, title: "เหตุที่ทำให้พระสัทธรรมตั้งอยู่ไม่นาน", anchor: "Mz7wtm3iYZ" },
    { id: 55, title: "เหตุที่ทำให้พระสัทธรรมตั้งอยู่ได้นาน", anchor: "e0aGAZDN26" },
    { id: 56, title: "การค้าขาย ๕ อย่างที่อุบาสกไม่ควรทำ", anchor: "aGjQuuKsIK" },
    { id: 57, title: "คนพูดมากมีโทษ ๕", anchor: "XYFN5DgYKL" },
    { id: 58, title: "คนพูดด้วยปัญญามีอานิสงส์ ๕", anchor: "WyGFZVAujU" },
    { id: 59, title: "โทษของความไม่อดทน ๕ ประการ", anchor: "8hdiklW1FR" },
    { id: 60, title: "อานิสงส์ของความอดทน ๕ ประการ", anchor: "vU7lBazlmd" },
    { id: 61, title: "อานิสงส์ในการฟังธรรม ๕ ประการ", anchor: "YoiBdnlBIm" },
    { id: 62, title: "อานิสงส์ของข้าวยาคู ๕ ประการ", anchor: "1ImU24wIF4" },
    { id: 63, title: "โทษในการไม่เคี้ยวไม้สีฟัน ๕ ประการ", anchor: "AhvcOmf40v" },
    { id: 64, title: "อานิสงส์ในการเคี้ยวไม้สีฟัน ๕ ประการ", anchor: "wZiznHAacS" },
    { id: 65, title: "โทษในการกล่าวธรรมด้วยเสียงขับอันยาวของภิกษุ", anchor: "ggECsF4S4h" },
    { id: 66, title: "โทษของผู้หลับโดยไม่มีสติสัมปชัญญะ", anchor: "4od9pcS91l" },
    { id: 67, title: "อานิสงส์ของผู้หลับโดยมีสติสัมปชัญญะ", anchor: "zkKh7C9kAh" },
    { id: 68, title: "อกุศลราศี (กองแห่งอกุศล)", anchor: "j7ytzLTVuN" },
    { id: 69, title: "ผู้บวชเมื่อแก่ที่มีคุณธรรม หาได้ยาก", anchor: "y9cECASth6" },
    { id: 70, title: "ผู้บวชเมื่อแก่ที่มีคุณธรรม หาได้ยากอีกประเภทหนึ่ง", anchor: "WUV3DcC1J0" },
    { id: 71, title: "สัมปทา (ความถึงพร้อมหรือความสมบูรณ์) ๕", anchor: "InnweVnqUw" },
    { id: 72, title: "คนที่เกิดมาเพื่อประโยชน์ความสุขแก่คนมาก", anchor: "YuFC4jTVvf" },
    { id: 73, title: "สิ่งที่ขอร้องหรือปรารถนาให้เป็นไปอย่างใจไม่ได้", anchor: "6H5xWgvEDZ" },
    { id: 74, title: "ที่ตั้งแห่งความอาฆาต ๑๐ อย่าง", anchor: "tMbscrgHhJ" },
    { id: 75, title: "เครื่องนำความอาฆาตออก ๑๐ อย่าง", anchor: "1vcdWgSxxd" },
    { id: 76, title: "พระพุทธเจ้าไม่ทรงสรรเสริญความหยุดอยู่ในกุศลธรรม", anchor: "Biho2rh8y3" },
    { id: 77, title: "ไม่ฉลาดในเรื่องจิตของผู้อื่น ก็ควรฉลาดในเรื่องจิตของตน", anchor: "NnN7xLHADz" },
    { id: 78, title: "ฉลาดในเรื่องจิตของตนอีกอย่างหนึ่ง", anchor: "HGqUK15mZr" },
    { id: 79, title: "ธรรมทั้งปวงมีอะไรเป็นอะไร", anchor: "MMf8cfzQp8" },
    { id: 80, title: "ละธรรม ๑๐ อย่างไม่ได้ ยังไม่ควรเป็นพระอรหันต์", anchor: "DMi8nBJe4R" },
    { id: 81, title: "ละธรรม ๑๐ อย่างได้ จึงควรเป็นพระอรหันต์", anchor: "V75OC6QjyU" },
    { id: 82, title: "คนที่เกิดมามีขวานเกิดมาในปากด้วย", anchor: "MM0iscb1RN" },
    { id: 100, title: "กำลัง ๗ ประการ (พละ ๗)", anchor: "Cd3Irb0RT0" },
    { id: 101, title: "คำอธิบายกำลัง ๗ ประการ", anchor: "8EVqR1PO8I" },
    { id: 125, title: "ความจนเป็นทุกข์ในโลก", anchor: "053IWvRkCF" },
    { id: 126, title: "ไตรลักษณ์มีอยู่แล้วโดยปกติ", anchor: "ChgcnI0Eum" },
    { id: 127, title: "ฤกษ์งามยามดี", anchor: "7Ndk7BstxQ" },
    { id: 128, title: "การแสวงหา ๒ อย่าง", anchor: "JsM5EJjj3H" },
    { id: 209, title: "ของแก้กันอย่างละ ๓", anchor: "kV4E9cuBdb" },
    { id: 210, title: "สุราเป็นเหตุให้ละเมิดศีลข้ออื่น ๆ", anchor: "IDClrHezH1" },
  ] as const,
  'khuddaka-nikaya': [
    { id: 2, title: "เกาะชายสังฆาฏิพระพุทธเจ้ายังไม่ชื่อว่าอยู่ใกล้", anchor: "ZZeI5noZPM" },
    { id: 3, title: "ศัตรูภายใน (โลภะ โทสะ โมหะ)", anchor: "JQTyNdN7Bo" },
    { id: 4, title: "อาคามี (ผู้มาเกิด) อนาคามี (ผู้ไม่มาเกิด) อรหันต์ (ผู้ไม่มีกิเลส)", anchor: "U1ZFP2fRsY" },
    { id: 5, title: "ภิกษุผู้มีกัลยาณศีล กัลยาณธรรม กัลยาณปัญญา", anchor: "jDvZqSfS2L" },
    { id: 6, title: "กองกระดูกเท่าภูเขา", anchor: "YAX4uaWxeR" },
    { id: 7, title: "ยังพูดปดทั้ง ๆ ที่รู้ จะไม่ทำความชั่วอย่างอื่นเป็นไปไม่ได้", anchor: "2TALjZy8li" },
    { id: 8, title: "มูลรากแห่งอกุศล ๓ อย่าง (โลภะ โทสะ โมหะ)", anchor: "c1vov7YF9n" },
    { id: 9, title: "พระธรรมเทศนา ๒ อย่าง", anchor: "NtIk4DVO5o" },
    { id: 10, title: "อะไรเป็นหัวหน้าอกุศลธรรมและกุศลธรรม", anchor: "NWavcs1uQu" },
    { id: 11, title: "อริยปัญญา", anchor: "1od35CBX3N" },
    { id: 12, title: "คำอธิบายเรื่อง \"ตถาคต\"", anchor: "PUShFmL2nY" },
    { id: 13, title: "ภิกษุ กับ คฤหัสถ์ ถ้อยทีถ้อยอาศัยกัน", anchor: "NhQYIXtcJJ" },
    { id: 14, title: "สกุลที่มีสิ่งศักดิ์สิทธิ์ประจำอยู่", anchor: "YdsUVYobfp" },
    { id: 17, title: "คำอธิบายนิพพานธาตุ ๒ อย่าง", anchor: "G5mMHXYNKK" },
    { id: 18, title: "ธรรมชาติที่ไม่เกิด ไม่ถูกปรุงแต่ง มีอยู่", anchor: "RaLqH6DnfH" },
    { id: 98, title: "ธรรมทั้งหลายมีใจเป็นหัวหน้า", anchor: "Ddwk7rQkOn" },
    { id: 99, title: "เวรย่อมระงับด้วยการไม่จองเวร", anchor: "MSUDByHMTc" },
    { id: 102, title: "มารย่อมข่มเหง และไม่ข่มเหงคนเช่นไร", anchor: "Lcd5A83gBc" },
    { id: 103, title: "กาสาวพัสตร์ กับกิเลสอันเปรียบเหมือนน้ำฝาด", anchor: "P1SjT68S07" },
    { id: 104, title: "จะบรรลุสิ่งเป็นสาระ ก็ด้วยเข้าใจสาระ", anchor: "qEO8gI9Tu4" },
    { id: 105, title: "ฝนรั่วรด ที่เทียบด้วยราคะ (ความติดใจ)", anchor: "HWTP0JLh5B" },
    { id: 106, title: "ผู้เศร้าโศก กับ ผู้บันเทิงในปัจจุบันและอนาคต", anchor: "5e7RKEZgnC" },
    { id: 107, title: "พูดมากไม่ทำ กับ พูดน้อยแต่ทำ", anchor: "MY8H7JFmFN" },
    { id: 108, title: "ความไม่ประมาท เป็นทางแห่งความไม่ตาย", anchor: "nfddjBxOVS" },
    { id: 109, title: "ยศเจริญแก่คนเช่นไร", anchor: "DeB9OMY7GU" },
    { id: 110, title: "เกาะชนิดไหนน้ำไม่ท่วม", anchor: "DlvvqC8QwH" },
    { id: 111, title: "คนพาล กับ คนมีปัญญา", anchor: "Cy5yEo8uhZ" },
    { id: 113, title: "ผู้เช่นไร บรรลุสุขอันไพบูล", anchor: "qWfiluqzqR" },
    { id: 114, title: "ขึ้นสู่ที่สูงมองดูคนข้างล่าง", anchor: "npS4teiDBF" },
    { id: 115, title: "ผู้มีปัญญา เหมือนม้ามีฝีเท้าเร็ว", anchor: "jpnShYb0HZ" },
    { id: 116, title: "ดีเหนือผู้อื่น ด้วยความไม่ประมาท", anchor: "IdENb2zM5C" },
    { id: 118, title: "ภิกษุผู้ยินดีในความไม่ประมาท", anchor: "ouJ3xBJXZH" },
    { id: 119, title: "ภิกษุผู้ยินดีในความไม่ประมาทอีกอย่างหนึ่ง", anchor: "9vjnuLRygo" },
    { id: 120, title: "จิตที่กวัดแกว่งดิ้นรนนั้นดัดให้ตรงได้", anchor: "E9LhLGzuhS" },
    { id: 121, title: "จิตที่ฝึกแล้วนำสุขมาให้", anchor: "oNXo976G4m" },
    { id: 122, title: "จิตที่คุ้มครองแล้วนำสุขมาให้", anchor: "sCp9OJUHMX" },
    { id: 123, title: "จะพ้นจากบ่วงมารได้อย่างไร", anchor: "B5iany9CPB" },
    { id: 124, title: "ผู้เช่นไร ปัญญาไม่รู้จักบริบูรณ์ ผู้เช่นไรไม่มีภัย", anchor: "Gai0ppYZ6X" },
    { id: 129, title: "นักรบทางธรรม", anchor: "r5Z9WWDnmu" },
    { id: 130, title: "อนาคตของกายนี้", anchor: "PUoKgnx4Eb" },
    { id: 131, title: "ใครทำร้ายก็ไม่เท่าจิตของตน", anchor: "y10jWzB1De" },
    { id: 132, title: "ใครทำดีให้ก็ไม่เท่าจิตของตน", anchor: "EGIZSZQ5HS" },
    { id: 133, title: "ผู้ชนะโลกทั้งสามและรู้จักเลือกเฟ้นธรรมะ", anchor: "olx96CVjud" },
    { id: 134, title: "ผู้ที่มัจจุราชมองไม่เห็น", anchor: "MD4jJpFIJd" },
    { id: 135, title: "ห้วงน้ำใหญ่ - มฤตยู", anchor: "4uYNpjX3KI" },
    { id: 136, title: "อำนาจของความตาย", anchor: "tc1TQGppQv" },
    { id: 153, title: "อะไรยาวนานสำหรับใคร", anchor: "eZkbezaphe" },
    { id: 154, title: "ความเป็นสหายในคนพาลไม่มี", anchor: "oiyoNXSPvA" },
    { id: 155, title: "ของเราแน่หรือ", anchor: "reWDEFtI02" },
    { id: 156, title: "พาลและบัณฑิตที่รู้จักตัวเอง", anchor: "uREMkGnLyl" },
    { id: 157, title: "ทัพพีไม่รู้รสแกง", anchor: "n31pX1U4n8" },
    { id: 158, title: "ลิ้นรู้รสแกง", anchor: "dgFpNCtioy" },
    { id: 159, title: "มีตนเป็นอมิตร", anchor: "myaGeTxB62" },
    { id: 160, title: "สะอาดด้วยน้ำ หรือ ด้วยความประพฤติ", anchor: "Dow4GwBzzk" },
    { id: 161, title: "อยู่ในอำนาจของคนอื่นเป็นทุกข์", anchor: "vuLtGVXGDo" },
    { id: 162, title: "สิ้นหลงย่อมไม่หวั่นไหว", anchor: "B9fTbHZ2KF" },
    { id: 163, title: "ไม่โศกในท่ามกลางแห่งความโศก", anchor: "EyShhxwTP7" },
    { id: 164, title: "อกเขา อกเรา", anchor: "ZZhvLPI8dy" },
    { id: 165, title: "ประวัติสุปพุทธะผู้เป็นโรคเรื้อน", anchor: "HEn4ncPJ1P" },
    { id: 166, title: "ถ้ากลัวทุกข์ก็อย่าทำความชั่ว", anchor: "fvm1e99GEf" },
    { id: 167, title: "คนค่อม แต่มีคุณธรรมสูง", anchor: "zHFYqTxORv" },
    { id: 168, title: "ลักษณะแห่งที่สุดทุกข์", anchor: "Q5Ki3COaIs" },
  ] as const,
  'abhidhamma-pitaka': [
    { id: 84, title: "ศีลวิบัติ ทิฏฐิวิบัติ", anchor: "aDLZspXjJ7" },
    { id: 85, title: "ศีลสัมปทา ทิฏฐิสัมปทา", anchor: "3LZLfN1EBd" },
    { id: 86, title: "ธรรมที่มีอารมณ์ และไม่มีอารมณ์", anchor: "kMV0Hxjgav" },
    { id: 87, title: "ธรรมที่เป็นจิต และไม่ใช่จิต", anchor: "4BAzO1EFly" },
    { id: 88, title: "ธรรมที่เป็นเจตสิก และไม่ใช่เจตสิก", anchor: "oWbiCg5Ki9" },
    { id: 89, title: "ธรรมที่ประกอบและไม่ประกอบกับจิต", anchor: "0Py5bnICOe" },
    { id: 90, title: "ธรรมที่ระคน และไม่ระคนกับจิต", anchor: "O3Qg5fsxE6" },
    { id: 91, title: "ธรรมที่มีจิตเป็นสมุฏฐาน และไม่มีจิตเป็นสมุฏฐาน", anchor: "ySpvr4GL3t" },
    { id: 92, title: "ธรรมที่เกิดพร้อมกับจิต และไม่เกิดพร้อมกับจิต", anchor: "TluNCIfWVS" },
    { id: 93, title: "ธรรมที่หมุนเวียนไปตามจิต และไม่หมุนเวียนไปตามจิต", anchor: "AYdiwuTuj9" },
    { id: 94, title: "ธรรมที่เป็นไปในภายใน และภายนอก", anchor: "Ii2Jmqfwi8" },
    { id: 95, title: "ธรรมที่เป็นกุศล", anchor: "bJwopWEVbH" },
    { id: 96, title: "ธรรมที่เป็นอกุศล", anchor: "GAQKK3xtZ4" },
    { id: 97, title: "ธรรมที่เป็นอัพยากฤต", anchor: "j86W2CLbIK" },
    { id: 171, title: "ธรรมที่มีความทะยานอยากเป็นมูล ๙ อย่าง", anchor: "PZUcJ0v0wN" },
    { id: 172, title: "เรื่องของกิเลส (เครื่องทำใจให้เศร้าหมอง) ๑๐ อย่าง", anchor: "kQ35WWp6rz" },
    { id: 186, title: "คำถามคำตอบเรื่องแจกหัวข้อธรรม", anchor: "AOnN1pLQTl" },
    { id: 187, title: "ขันธ์ (กอง) ๕ มีอะไรบ้าง", anchor: "3FjaX96tVn" },
    { id: 188, title: "อายตนะ (ที่ต่อ) ๑๒ มีอะไรบ้าง", anchor: "41f53qbfof" },
    { id: 189, title: "ธาตุ ๑๘ มีอะไรบ้าง", anchor: "gqTxGbFkWl" },
    { id: 190, title: "สัจจะ ๔ มีอะไรบ้าง", anchor: "VtGSDzwkAm" },
    { id: 191, title: "อินทรีย์ ๒๒ มีอะไรบ้าง", anchor: "6TxLNj1QPe" },
    { id: 192, title: "เหตุ ๙ มีอะไรบ้าง", anchor: "n2kXIghimA" },
    { id: 193, title: "อาหาร ๔ มีอะไรบ้าง", anchor: "wVyvS1t7qw" },
    { id: 194, title: "ผัสสะ (ความถูกต้อง) ๗ มีอะไรบ้าง", anchor: "Q6AMA6p4n0" },
    { id: 195, title: "เวทนา (ความรู้สึกสุข ทุกข์หรือเฉย ๆ) ๗ มีอะไรบ้าง", anchor: "TGOJVnAXzG" },
    { id: 196, title: "สัญญา (ความจำ) ๗ มีอะไรบ้าง", anchor: "MUaQchzAgL" },
    { id: 197, title: "เจตนา (ความจงใจ) ๗ มีอะไรบ้าง", anchor: "n8ETBGIhLB" },
    { id: 198, title: "จิต ๗ มีอะไรบ้าง", anchor: "YFfV7pmQJt" },
  ] as const,
} as const

export type Part3PitakaKey = keyof typeof PART3_PITAKA_PASSAGES

export type Part3PassageEntry = (typeof PART3_PITAKA_PASSAGES)[Part3PitakaKey][number]
